modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/randysdoom/Evolution/issues"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="A Trip Through The Ages"
authors="Randysdoom"
[[mods]]
modId="evolution"
version="1.0.0"
displayName="Evolution"
description='''A trip through the ages.'''
[[dependencies.evolution]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
